spring:
  application:
    name: avro-tutorial
kafka:
  retro-topic: ${KAFKA_RETRO_TOPIC:trn-tickets-retro}
  reprocess-topic: ${KAFKA_REPROCESS_TOPIC:trn-tickets-retro-reprocess}
  bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
  consumer:
    concurrency: 3
    poll-timeout: 3000
    max-poll-records: 1000
    batch-listener: true